app.controller('HomeController', function($scope) {
    {

        $scope.add = function() {
            $scope.data.push({
                'motor': $scope.addData.motor,
                'nkonsumen': $scope.addData.nkonsumen,
                'hp': $scope.addData.hp,
                'telp1': $scope.addData.telp1,
                'telp2': $scope.addData.telp2,
            })
            $scope.addData = {}
        }

        $scope.data = [{
                "ntahun": "0.75",
                "tymotor1": "MATIC NEX                ",
                "NCABANG": "",
                "nwilayah": "SULAWESI TENGGARA             ",
                "tglfkt": "2021-01-05",
                "nkonsumen": "FERA SUSANTI.H                                              ",
                "norang": "154685              ",
                "nomes": "452170              ",
                "tymotor": "UX110NER1      ",
                "alamat": "JL.BERINGIN I KEL.KENDARI CADDI KEC.KENDARI KOTA KENDARI",
                "hp": "            ",
                "telp": "            ",
                "hpservicer": "            ",
                "motor": "MATIC NEX                ",
                "telp1": "            ",
                "n_service": "0",
                "stcall": "0",
                "status": "9",
                "stempel": "2021-09-08 12:06:41"
            },
            {
                "ntahun": "0.75",
                "tymotor1": "MATIC NEX                ",
                "NCABANG": "",
                "nwilayah": "SULAWESI BARAT",
                "tglfkt": "2021-01-05",
                "nkonsumen": "MU MING                                                     ",
                "norang": "138311              ",
                "nomes": "538257              ",
                "tymotor": "UX110NEFD      ",
                "alamat": "LINGK ALLA-ALLA KEL.RANGAS KEC.SIMBORO KAB.MAMUJU",
                "hp": "            ",
                "telp": "",
                "hpservicer": "",
                "motor": "MATIC NEX                ",
                "telp1": "            ",
                "n_service": "0",
                "stcall": null,
                "status": null,
                "stempel": null
            },
            {
                "ntahun": "0.74",
                "tymotor1": "MATIC NEX                ",
                "NCABANG": "",
                "nwilayah": "SULAWESI SELATAN",
                "tglfkt": "2021-01-06",
                "nkonsumen": "FRANSISCA LOMEWA                                            ",
                "norang": "146242              ",
                "nomes": "450003              ",
                "tymotor": "UX110NER ACCS  ",
                "alamat": "JL.RAYA LANTO KEL.PALLANTIKANG KEC.BANTAENG KAB.BANTAENG",
                "hp": "085399933900",
                "telp": "            ",
                "hpservicer": "            ",
                "motor": "MATIC NEX                ",
                "telp1": "",
                "n_service": "0",
                "stcall": null,
                "status": null,
                "stempel": null
            },
            {
                "ntahun": "0.74",
                "tymotor1": "MOTORSPORT               ",
                "NCABANG": "",
                "nwilayah": "SULAWESI TENGGARA             ",
                "tglfkt": "2021-01-07",
                "nkonsumen": "M U K M I N                                                 ",
                "norang": "151849              ",
                "nomes": "155321              ",
                "tymotor": "GSX-R150RFXK   ",
                "alamat": "DESA GALU KEC.SAMPARA KAB.KONAWE",
                "hp": "            ",
                "telp": "            ",
                "hpservicer": "            ",
                "motor": "MOTORSPORT               ",
                "telp1": "",
                "n_service": "0",
                "stcall": null,
                "status": null,
                "stempel": null
            },
            {
                "ntahun": "0.73",
                "tymotor1": "MATIC NEX                ",
                "NCABANG": "",
                "nwilayah": "SULAWESI SELATAN",
                "tglfkt": "2021-01-11",
                "nkonsumen": "DRS APRISAL.MSI                                             ",
                "norang": "154644              ",
                "nomes": "452132              ",
                "tymotor": "UX110NER1      ",
                "alamat": "BTN CABALU BLOK C3/3 KEL.PAENRE LOMPOE KEC.GANTARANG KAB.BULUKUMBA",
                "hp": "",
                "telp": "",
                "hpservicer": "",
                "motor": "MATIC NEX                ",
                "telp1": "",
                "n_service": "0",
                "stcall": null,
                "status": null,
                "stempel": null
            },
            {
                "ntahun": "0.73",
                "tymotor1": "MATIC NEX                ",
                "NCABANG": "",
                "nwilayah": "SULAWESI SELATAN",
                "tglfkt": "2021-01-11",
                "nkonsumen": "H.DJALLU                                                    ",
                "norang": "146892              ",
                "nomes": "450525              ",
                "tymotor": "UX110NER       ",
                "alamat": "PANRANGLOHE DESA BONTOKAMASE KEC.HERLANG KAB.BULUKUMBA",
                "hp": "               ",
                "telp": "            ",
                "hpservicer": "            ",
                "motor": "MATIC NEX                ",
                "telp1": "",
                "n_service": "0",
                "stcall": null,
                "status": null,
                "stempel": null
            },
            {
                "ntahun": "0.73",
                "tymotor1": "MATIC NEX                ",
                "NCABANG": "PT. SINAR GALESONG MANDIRI - KENDARI         ",
                "nwilayah": "SULAWESI TENGGARA             ",
                "tglfkt": "2021-01-12",
                "nkonsumen": "ANDI ROSDIANA.M                                             ",
                "norang": "155438              ",
                "nomes": "552984              ",
                "tymotor": "UX110NE1       ",
                "alamat": "JL.DR.SAM RATULANGI NO.188 I KEL.MANDONGA KEC.MANDONGA KOTA KENDARI",
                "hp": "08123030212    ",
                "telp": "082142536097",
                "hpservicer": "082142536097",
                "motor": "MATIC NEX                ",
                "telp1": "",
                "n_service": "0",
                "stcall": null,
                "status": null,
                "stempel": null
            }
        ]
    }
})